name: DevSecOps Security Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sast-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Semgrep SAST Scan
        run: |
          docker run --rm -v "${PWD}:/src" semgrep/semgrep semgrep --config="p/owasp-top-ten" --error .

  sca-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run Snyk SCA Scan for Python dependencies
        uses: snyk/actions/python@master
        env:
          # Adicione o token do Snyk nos Secrets do seu repositório
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --file=app/requirements.txt --fail-on=high --severity-threshold=high

  build-and-run-for-dast:
    runs-on: ubuntu-latest
    # Este job depende dos scans estáticos passarem
    needs: [sast-analysis, sca-analysis]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t financial-api:latest .

      - name: Run application in background
        # Roda o container e dá a ele o nome 'api' para ser encontrado pelo ZAP
        run: docker run -d --name api -p 8000:8000 financial-api:latest
      
      - name: Wait for application to start
        # DAST precisa que a API esteja pronta para receber requisições
        run: sleep 15

  dast-analysis:
    runs-on: ubuntu-latest
    # Roda somente após a aplicação subir
    needs: build-and-run-for-dast
    steps:
      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --rm -v $(pwd):/zap/wrk/:rw --network="host" \
          owasp/zap2docker-stable zap-baseline.py -t http://127.0.0.1:8000 -r report.html
          
          # Se o ZAP encontrar alertas, ele retorna um código de erro.
          # O '|| true' abaixo evita que o pipeline quebre por enquanto.
          # Remova o '|| true' quando quiser que o pipeline falhe com vulnerabilidades.
          || true
